### ISSUE TITLE
MemDB.ReverseIterator does not iterate properly (skips item)

### ISSUE THREAD

**Issue by ridenaio** [tendermint/tm-db#86]
We have updated package to `github.com/tendermint/tm-db@0.5.1`, previously we had  `github.com/tendermint/tm-db@0.4.0`.

Now, this test fails. Two same `getItems` calls return different results. On version 0.4.0 this test was successful.

```
func Test_MemDb(t *testing.T) {
	db := NewMemDB()

	getItems := func(count int, end []byte) ([][]byte, []byte) {
		var data [][]byte

		// we append 255 byte to the end, because end is exclusive
		it, _ := db.ReverseIterator([]byte{0, 0}, append(end, byte(255)))
		defer it.Close()
		for ; it.Valid(); it.Next() {
			key, value := it.Key(), it.Value()
			if len(data) == count {
				return data, key[:1]
			}
			data = append(data, value)
		}
		return data, nil
	}

	for i := 1; i <= 5; i++ {
		db.Set([]byte{byte(i), byte(i)}, []byte{byte(i)})
	}

	// now we have
	// a - key: [1, 1], value: [1]
	// b - key: [2, 2], value: [2]
	// c - key: [3, 3], value: [3]
	// d - key: [4, 4], value: [4]
	// e - key: [5, 5], value: [5]

	// start with key 5
	// iterator will be - start: [0, 0], end: [5, 255]
	// should return values from entities: "e", "d"
	// [5, 255] is exclusive. [5, 5] is less than [5, 255].
	end := []byte{5}
	data, continuationToken := getItems(2, end)
	require.Equal(t, [][]uint8{{5}, {4}}, data)

	// start with key 3
	// iterator will be - start: [0, 0], end: [3, 255]
	// should return values from entities: "c", "b"
	// [3, 255] is exclusive. [3, 3] is less than [3, 255].
	// but tests fails and returns entities "b", "a". Entity "c" is skipped for some reason.
	data, continuationToken = getItems(2, continuationToken)
	require.Equal(t, [][]uint8{{3}, {2}}, data)
}
```

**Comment by erikgrinaker** [comment]
Thanks for for the report, we'll have a look!

**Comment by erikgrinaker** [comment]
Hi @ridenaio! This turned out to be a bug in your test-case. The documentation for `Key()` and `Value()` says that the returned values are to be considered read-only:

https://godoc.org/github.com/tendermint/tm-db#Iterator

However, you are returning a pointer to the key from `getItems()` at `return data, key[:1]`, then passing this key back into the next `getItems()` call as `continuationToken`, and then appending to the key as `append(end, byte(255))`. This `append()` call will, depending on the layout of the backing byte slice, actually modify the input slice.

In this case, `append(env, byte(255))` modifies the key in the memory database from `[]byte{3}` to `[]byte{3, 255}`, such that when iterating the end `{3, 255}` matches the modified key in the database and is skipped since the end is exclusive.

One way to fix this is to make sure you return a copy of the key as the continuation token, e.g.:

```go
key, value := it.Key(), it.Value()
if len(data) == count {
	continuationToken := make([]byte, len(key)-1)
	copy(continuationToken, key)
	return data, continuationToken
}
```

We do not implicitly copy all returned keys and values since this would have a high performance penalty.
